FROM grafana/grafana

# candlestick chats, various other financial plots
ENV GF_INSTALL_PLUGINS="grafana-candlestick-panel,natel-plotly-panel"

ENV GF_PATHS_PROVISIONING="/etc/grafana/provisioning"
